name: Broker Image CI

env: 
  ACR: charrisagoracr.azurecr.io
  IMAGE: mqtt-broker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with: 
          registry: ${{ env.ACR }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with: 
          context: "${{defaultContext}}:${{env.IMAGE}}"
          file: "${{env.IMAGE}}/Dockerfile"
          push: true
          build-args: |
            version=latest
          tags: ${{env.ACR}}/${{env.IMAGE}}:latest
