name: Broker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Broker image
      working-directory: mqtt-broker
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
