name: Simulator Image CI

env: 
  ACR: charrisagoracr.azurecr.io
  IMAGE: mqtt-simulator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:

      - name: Login to registry
        uses: docker/login-action@v2
        with: 
          registry: ${{ env.ACR }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx # Required for subdirectory support
        uses: docker/setup-buildx-action@v2

      - name: Build & Push
        uses: docker/build-push-action@v2
        with: 
          context: "{{defaultContext}}:${{env.IMAGE}}"
          push: true
          build-args: |
            version=latest
          tags: ${{env.ACR}}/${{env.IMAGE}}:latest
