name: Simulator Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Simulator image
      run: docker build ./mqtt-simulator --file Dockerfile --tag my-image-name:$(date +%s)
